include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    avoid_redundant_argument_values: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_super_parameters: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
