"""AI Guardian router — Predictive Safety Intelligence endpoints.

TODO: Add authentication via get_current_user once frontend auth flow is wired up.
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime, date

router = APIRouter()


# ── Pydantic response models ───────────────────────────────────────────────────

class SafetyScore(BaseModel):
    category: str
    score: int
    max_score: int
    status: str           # "safe" | "warning" | "alert"
    badge: Optional[str]  # e.g. "Low", "Moderate", "High"
    color: str            # hex colour for frontend
    note: Optional[str]


class SafetyScoresResponse(BaseModel):
    family_id: int
    overall_score: int
    generated_at: str
    scores: List[SafetyScore]


class ReportEvent(BaseModel):
    time: str
    member: str
    event: str
    status: str    # "safe" | "warning" | "alert"
    category: str  # "location" | "health" | "driving" | "routine"


class DailyReportResponse(BaseModel):
    family_id: int
    report_date: str
    ai_summary: str
    overall_score: int
    events: List[ReportEvent]
    recommendations: List[str]


class InsightItem(BaseModel):
    id: int
    icon_type: str   # "check" | "heart" | "car" | "map" | "alert" | "brain"
    dot_color: str
    text: str
    time: str
    priority: str    # "low" | "medium" | "high"


class InsightsResponse(BaseModel):
    family_id: int
    generated_at: str
    insights: List[InsightItem]
    total_signals_processed: int


class AskRequest(BaseModel):
    query: str
    family_id: int
    context: Optional[str] = None


class AskResponse(BaseModel):
    query: str
    family_id: int
    response: str
    confidence: float
    related_members: List[str]
    action_items: List[str]
    generated_at: str


class RiskPrediction(BaseModel):
    risk_type: str
    title: str
    description: str
    probability: float   # 0.0 – 1.0
    severity: str        # "low" | "medium" | "high" | "critical"
    affected_member: Optional[str]
    recommendation: str
    predicted_for: str   # ISO date string


class RiskPredictionsResponse(BaseModel):
    user_id: int
    generated_at: str
    predictions: List[RiskPrediction]
    next_24h_risk_score: int


# ── Helpers ────────────────────────────────────────────────────────────────────

def _now_iso() -> str:
    return datetime.utcnow().isoformat() + "Z"


def _today_iso() -> str:
    return date.today().isoformat()


# ── Endpoints ──────────────────────────────────────────────────────────────────

@router.get(
    "/ai-guardian/safety-scores/{family_id}",
    response_model=SafetyScoresResponse,
    summary="Get real-time safety scores for a family",
)
async def get_safety_scores(family_id: int):
    """
    Returns predictive safety scores for every monitored category of the family.
    Scores are generated by the AI engine based on recent activity patterns.

    TODO: Authenticate caller — verify caller belongs to the requested family.
    """
    if family_id <= 0:
        raise HTTPException(status_code=422, detail="family_id must be a positive integer")

    scores: List[SafetyScore] = [
        SafetyScore(
            category="route_safety",
            score=94, max_score=100,
            status="safe", badge=None,
            color="#10B981",
            note="All family routes are within expected patterns today.",
        ),
        SafetyScore(
            category="child_risk",
            score=97, max_score=100,
            status="safe", badge="Low",
            color="#3B82F6",
            note=None,
        ),
        SafetyScore(
            category="elderly_risk",
            score=62, max_score=100,
            status="warning", badge="Moderate",
            color="#F59E0B",
            note="High Fall Risk in Rain — heartrate elevated this morning.",
        ),
        SafetyScore(
            category="driving_risk",
            score=23, max_score=100,
            status="safe", badge=None,
            color="#10B981",
            note="2 harsh brake events detected. Overall score remains safe.",
        ),
        SafetyScore(
            category="health_risk",
            score=12, max_score=100,
            status="safe", badge=None,
            color="#10B981",
            note=None,
        ),
        SafetyScore(
            category="emergency_probability",
            score=8, max_score=100,
            status="safe", badge="Low",
            color="#10B981",
            note="No emergency indicators in the last 6 hours.",
        ),
    ]

    overall = round(sum(s.score for s in scores) / len(scores))

    return SafetyScoresResponse(
        family_id=family_id,
        overall_score=overall,
        generated_at=_now_iso(),
        scores=scores,
    )


@router.get(
    "/ai-guardian/daily-report/{family_id}",
    response_model=DailyReportResponse,
    summary="Get today's AI-generated family safety report",
)
async def get_daily_report(family_id: int):
    """
    Returns the AI-generated daily safety report for a family including a
    complete timeline of events and personalised recommendations.

    TODO: Authenticate caller — verify caller belongs to the requested family.
    """
    if family_id <= 0:
        raise HTTPException(status_code=422, detail="family_id must be a positive integer")

    events: List[ReportEvent] = [
        ReportEvent(
            time="7:15 AM", member="Grandma",
            event="Completed morning walk — 1.8 km in 28 minutes. Heart rate normal.",
            status="safe", category="health",
        ),
        ReportEvent(
            time="8:42 AM", member="Aanya",
            event="Arrived at St. Mary's School safely via expected route.",
            status="safe", category="location",
        ),
        ReportEvent(
            time="9:15 AM", member="Dad",
            event="Entered office geofence zone. Commute: 34 minutes.",
            status="safe", category="location",
        ),
        ReportEvent(
            time="10:15 AM", member="Grandma",
            event="Elevated heartrate detected — AI recommends rest. Smartwatch alert sent.",
            status="warning", category="health",
        ),
        ReportEvent(
            time="11:30 AM", member="Rohan",
            event="2 harsh brake events detected during school commute. Driving score: 67/100.",
            status="alert", category="driving",
        ),
        ReportEvent(
            time="3:45 PM", member="Aanya",
            event="Left school — on expected route home. ETA 4:05 PM.",
            status="safe", category="location",
        ),
    ]

    return DailyReportResponse(
        family_id=family_id,
        report_date=_today_iso(),
        ai_summary=(
            "Family safety is above average today (score 87/100). "
            "Grandma requires attention due to elevated heartrate. "
            "Rohan's driving needs a review — 2 harsh brake events logged. "
            "All other members are on schedule and within safe zones."
        ),
        overall_score=87,
        events=events,
        recommendations=[
            "Schedule a driving safety review with Rohan this weekend.",
            "Remind Grandma to rest and stay hydrated this afternoon.",
            "Rain forecast for tomorrow — suggest Aanya takes the covered route to school.",
            "Dad's commute stress indicator is elevated — recommend evening relaxation.",
        ],
    )


@router.get(
    "/ai-guardian/insights/{family_id}",
    response_model=InsightsResponse,
    summary="Get AI-generated real-time insights for a family",
)
async def get_insights(family_id: int):
    """
    Returns a list of AI-generated insights for the family, ranked by priority.
    Each insight is derived from pattern analysis of the last 24 hours.

    TODO: Authenticate caller — verify caller belongs to the requested family.
    """
    if family_id <= 0:
        raise HTTPException(status_code=422, detail="family_id must be a positive integer")

    insights: List[InsightItem] = [
        InsightItem(
            id=1, icon_type="check", dot_color="#10B981",
            text="Aanya arrived at school safely at 8:42 AM",
            time="8:42 AM", priority="low",
        ),
        InsightItem(
            id=2, icon_type="heart", dot_color="#F59E0B",
            text="Grandma's heartrate elevated — recommend rest",
            time="10:15 AM", priority="medium",
        ),
        InsightItem(
            id=3, icon_type="car", dot_color="#EF4444",
            text="Teen driver Rohan: 2 harsh brakes detected",
            time="11:30 AM", priority="high",
        ),
        InsightItem(
            id=4, icon_type="map", dot_color="#A78BFA",
            text="Geofence: Dad entered office zone at 9:15 AM",
            time="9:15 AM", priority="low",
        ),
        InsightItem(
            id=5, icon_type="brain", dot_color="#D4A853",
            text="AI pattern: Family routine adherence is 94% this week",
            time="12:00 PM", priority="low",
        ),
        InsightItem(
            id=6, icon_type="alert", dot_color="#EC4899",
            text="Weather alert: Heavy rain forecast for tomorrow — child route safety may drop",
            time="2:00 PM", priority="medium",
        ),
    ]

    return InsightsResponse(
        family_id=family_id,
        generated_at=_now_iso(),
        insights=insights,
        total_signals_processed=2847,
    )


@router.post(
    "/ai-guardian/ask",
    response_model=AskResponse,
    summary="Ask AI Guardian a natural-language safety question",
)
async def ask_ai_guardian(body: AskRequest):
    """
    Accepts a natural-language query and returns a simulated AI response with
    family safety context. Supports questions about location, health, driving,
    emergencies, and general family status.

    TODO: Authenticate caller — verify caller belongs to the requested family.
    TODO: Integrate with real LLM (e.g., Anthropic Claude) for production responses.
    """
    if not body.query.strip():
        raise HTTPException(status_code=422, detail="query must not be empty")

    q = body.query.lower()

    # Simulate AI response routing based on query keywords
    if any(k in q for k in ["aanya", "child", "school", "kid"]):
        response = (
            "Aanya is at St. Mary's School, Mumbai — arrived 8:42 AM via the expected route. "
            "Currently in the main building. All clear. No deviations detected today."
        )
        members = ["Aanya"]
        actions = ["View Aanya's live location", "Set school arrival alert"]

    elif any(k in q for k in ["grandma", "grandmother", "elderly", "nani", "dadi"]):
        response = (
            "Grandma completed her morning walk at 7:15 AM — 1.8 km, heartrate normal during walk. "
            "Heartrate elevated at 10:15 AM (90 bpm). She is home now. "
            "AI recommends rest and hydration this afternoon."
        )
        members = ["Grandma"]
        actions = ["View Grandma's health data", "Send wellness reminder", "Call Grandma"]

    elif any(k in q for k in ["rohan", "teen", "driving", "car", "brake"]):
        response = (
            "Rohan has 2 harsh brake events logged today at 11:30 AM. "
            "Current driving score: 67/100 — below safe threshold. "
            "Phone was in pocket during both events. Recommend a driving safety conversation."
        )
        members = ["Rohan"]
        actions = ["View driving report", "Schedule safety review", "Enable speed alerts"]

    elif any(k in q for k in ["dad", "father", "papa", "office"]):
        response = (
            "Dad arrived at the office geofence at 9:15 AM. "
            "Commute time: 34 minutes — 6 minutes above usual. "
            "He is currently in the office zone. Commute stress indicator slightly elevated."
        )
        members = ["Dad"]
        actions = ["View Dad's location", "Check commute history"]

    elif any(k in q for k in ["emergency", "sos", "help", "danger", "urgent"]):
        response = (
            "No active SOS alerts right now. "
            "1 warning: Rohan had 2 harsh brake events this morning. "
            "Grandma's heartrate was elevated — she is resting at home. "
            "No critical emergencies detected in the last 6 hours."
        )
        members = ["All members"]
        actions = ["View all alerts", "Test SOS button", "Update emergency contacts"]

    elif any(k in q for k in ["everyone", "all", "family", "where", "location"]):
        response = (
            "All 5 family members are located and accounted for. "
            "Aanya: School. Dad: Office. Rohan: Near school area. "
            "Grandma: Home (resting). Mom: Home. "
            "No geofence violations. 1 driving warning for Rohan."
        )
        members = ["Aanya", "Dad", "Rohan", "Grandma", "Mom"]
        actions = ["View family map", "Set group check-in"]

    elif any(k in q for k in ["score", "safety", "risk", "how safe"]):
        response = (
            "Today's family safety score is 87/100 — above average. "
            "Child safety: 97 (excellent). Elder wellness: 72 (needs attention). "
            "Driving safety: 67 (review Rohan). Route safety: 94 (safe). "
            "Overall trend is positive this week."
        )
        members = []
        actions = ["View full safety report", "Download weekly summary"]

    else:
        response = (
            "All family members are safe right now. No active SOS alerts. "
            "1 driving warning for Rohan. Grandma's heartrate is slightly elevated — "
            "she's resting at home. Ask me about any specific family member for more details."
        )
        members = []
        actions = ["View family dashboard", "View today's report"]

    return AskResponse(
        query=body.query,
        family_id=body.family_id,
        response=response,
        confidence=0.94,
        related_members=members,
        action_items=actions,
        generated_at=_now_iso(),
    )


@router.get(
    "/ai-guardian/risk-predictions/{user_id}",
    response_model=RiskPredictionsResponse,
    summary="Get AI risk predictions for a specific user",
)
async def get_risk_predictions(user_id: int):
    """
    Returns risk predictions for a specific user based on 14-day pattern analysis.
    Predictions cover route safety, health, driving, and environmental risks.

    TODO: Authenticate caller — verify the user belongs to the caller's family.
    """
    if user_id <= 0:
        raise HTTPException(status_code=422, detail="user_id must be a positive integer")

    tomorrow = date.today().isoformat()

    predictions: List[RiskPrediction] = [
        RiskPrediction(
            risk_type="weather_route",
            title="Rain + Child Route Risk",
            description=(
                "Heavy rain forecast tomorrow. Aanya's current school route has 3 sections "
                "without covered footpaths. Predicted route safety score drop: 94 → 72."
            ),
            probability=0.78,
            severity="medium",
            affected_member="Aanya",
            recommendation="Switch to covered bus route (Route 47B) or arrange pickup.",
            predicted_for=tomorrow,
        ),
        RiskPrediction(
            risk_type="driving_fatigue",
            title="Dad Friday Driving Pattern",
            description=(
                "Historical data shows 73% higher speed violations on Friday evenings. "
                "Late meeting scheduled today increases fatigue probability."
            ),
            probability=0.65,
            severity="medium",
            affected_member="Dad",
            recommendation="Suggest leaving office by 6 PM to avoid peak fatigue window.",
            predicted_for=tomorrow,
        ),
        RiskPrediction(
            risk_type="elderly_health",
            title="Grandma Wellness Decline",
            description=(
                "Heartrate elevated today. 7-day trend shows 12% reduction in walking distance. "
                "Pattern matches pre-illness indicators from 3 months ago."
            ),
            probability=0.55,
            severity="medium",
            affected_member="Grandma",
            recommendation="Schedule a doctor visit this week. Monitor hydration and rest.",
            predicted_for=tomorrow,
        ),
        RiskPrediction(
            risk_type="teen_driving",
            title="Rohan Driving Risk Elevated",
            description=(
                "2 harsh brake events today. This is the 3rd occurrence this week. "
                "Pattern analysis indicates distracted driving, not route hazards."
            ),
            probability=0.82,
            severity="high",
            affected_member="Rohan",
            recommendation="Enable distracted driving alerts and schedule a family safety talk.",
            predicted_for=tomorrow,
        ),
        RiskPrediction(
            risk_type="routine_deviation",
            title="Weekend Routine Change",
            description=(
                "Saturday morning family routine adherence drops by 34% on average. "
                "Lower predictability increases monitoring workload for AI Guardian."
            ),
            probability=0.90,
            severity="low",
            affected_member=None,
            recommendation="Set weekend check-in reminders at 10 AM and 6 PM.",
            predicted_for=tomorrow,
        ),
    ]

    # Calculate aggregate 24h risk score
    weighted_risk = sum(p.probability * (3 if p.severity == "high" else 2 if p.severity == "medium" else 1) for p in predictions)
    next_24h_score = min(100, int(weighted_risk * 10))

    return RiskPredictionsResponse(
        user_id=user_id,
        generated_at=_now_iso(),
        predictions=predictions,
        next_24h_risk_score=next_24h_score,
    )
